In [1]:
import numpy as np
import pandas as pd

works = pd.DataFrame({
    '작가': ['김유정', '김유정', '김유정',
            '현진건', '현진건',
            '이상', '이상',
            '나도향', '나도향',
            '채만식', '이효석'],
    '작품': ['봄봄', '동백꽃', '만무방',
            '운수 좋은 날', 'B사감과 러브레터',
            '날개', '권태',
            '벙어리 삼룡이', '물레방아',
            '레디메이드 인생', '메밀꽃 필 무렵'],
    '연도': [1935, 1936, 1934,
            1924, 1925,
            1936, 1937,
            1925, 1925,
            1934, np.nan], # 이효석 '메밀꽃 필 무렵' 발표연도가 누락됨
    '글자수': [12500, 9800, 13600,
                11200, 7400,
                18300, 14100,
                16800, 14500,
                22000, 11800],
})

authors = pd.DataFrame({
    '작가': ['김유정', '현진건', '이상', '나도향', '채만식', '이효석', '염상섭'],
    '생년': [1908, 1900, 1910, 1902, 1902, 1907, 1897],
    '몰년': [1937, 1943, 1937, 1926, 1950, 1942, 1963],
})

In [2]:
#Q1

works.shape

(11, 4)

In [3]:
works.dtypes

작가         str
작품         str
연도     float64
글자수      int64
dtype: object

연도 열에 NaN이 포함되어 있는데 NaN이 섞이면 정수 열도 float이 된다.

In [4]:
works.describe()

                연도           글자수
count    10.000000     11.000000
mean   1931.100000  13818.181818
std       5.546771   4080.641661
min    1924.000000   7400.000000
25%    1925.000000  11500.000000
50%    1934.000000  13600.000000
75%    1935.750000  15650.000000
max    1937.000000  22000.000000

In [5]:
works.isna().sum()

작가     0
작품     0
연도     1
글자수    0
dtype: int64

In [6]:
works2 = works.fillna(1936)
works2

     작가         작품      연도    글자수
0   김유정         봄봄  1935.0  12500
1   김유정        동백꽃  1936.0   9800
2   김유정        만무방  1934.0  13600
3   현진건    운수 좋은 날  1924.0  11200
4   현진건  B사감과 러브레터  1925.0   7400
5    이상         날개  1936.0  18300
6    이상         권태  1937.0  14100
7   나도향    벙어리 삼룡이  1925.0  16800
8   나도향       물레방아  1925.0  14500
9   채만식   레디메이드 인생  1934.0  22000
10  이효석   메밀꽃 필 무렵  1936.0  11800

In [7]:
works2['연도'].astype(int)

0     1935
1     1936
2     1934
3     1924
4     1925
5     1936
6     1937
7     1925
8     1925
9     1934
10    1936
Name: 연도, dtype: int64

In [8]:
works2.dtypes

작가         str
작품         str
연도     float64
글자수      int64
dtype: object

In [9]:
works2.tail(3)

     작가        작품      연도    글자수
8   나도향      물레방아  1925.0  14500
9   채만식  레디메이드 인생  1934.0  22000
10  이효석  메밀꽃 필 무렵  1936.0  11800

In [10]:
#Q2

after_1930= works2[works2['연도']>=1930]
after_1930

     작가        작품      연도    글자수
0   김유정        봄봄  1935.0  12500
1   김유정       동백꽃  1936.0   9800
2   김유정       만무방  1934.0  13600
5    이상        날개  1936.0  18300
6    이상        권태  1937.0  14100
9   채만식  레디메이드 인생  1934.0  22000
10  이효석  메밀꽃 필 무렵  1936.0  11800

In [11]:
kim_or_lee = works2[works2['작가'].isin(['김유정','이상'])]
kim_or_lee

    작가   작품      연도    글자수
0  김유정   봄봄  1935.0  12500
1  김유정  동백꽃  1936.0   9800
2  김유정  만무방  1934.0  13600
5   이상   날개  1936.0  18300
6   이상   권태  1937.0  14100

In [12]:
def categorize(n: int) -> str:
    if n > 15000: return '긴'
    if n >= 10000: return '보통'
    return '짧음'    
    
works2['분량'] = works2['글자수'].apply(categorize)

In [13]:
works2[['작품', '글자수', '분량']]

           작품    글자수  분량
0          봄봄  12500  보통
1         동백꽃   9800  짧음
2         만무방  13600  보통
3     운수 좋은 날  11200  보통
4   B사감과 러브레터   7400  짧음
5          날개  18300   긴
6          권태  14100  보통
7     벙어리 삼룡이  16800   긴
8        물레방아  14500  보통
9    레디메이드 인생  22000   긴
10   메밀꽃 필 무렵  11800  보통

In [14]:
works2.sort_values(['연도', '글자수'], ascending=[True, False])

     작가         작품      연도    글자수  분량
3   현진건    운수 좋은 날  1924.0  11200  보통
7   나도향    벙어리 삼룡이  1925.0  16800   긴
8   나도향       물레방아  1925.0  14500  보통
4   현진건  B사감과 러브레터  1925.0   7400  짧음
9   채만식   레디메이드 인생  1934.0  22000   긴
2   김유정        만무방  1934.0  13600  보통
0   김유정         봄봄  1935.0  12500  보통
5    이상         날개  1936.0  18300   긴
10  이효석   메밀꽃 필 무렵  1936.0  11800  보통
1   김유정        동백꽃  1936.0   9800  짧음
6    이상         권태  1937.0  14100  보통

In [15]:
#Q3

works2.groupby('작가')['글자수'].agg(['mean', 'count', 'sum']) # 학과별 국어 평균

             mean  count    sum
작가
김유정  11966.666667      3  35900
나도향  15650.000000      2  31300
이상   16200.000000      2  32400
이효석  11800.000000      1  11800
채만식  22000.000000      1  22000
현진건   9300.000000      2  18600

In [16]:
print(works2['분량'].value_counts())

분량
보통    6
긴     3
짧음    2
Name: count, dtype: int64

In [17]:
works2.groupby(['작가', '분량']).size()

작가   분량
김유정  보통    2
     짧음    1
나도향  긴     1
     보통    1
이상   긴     1
     보통    1
이효석  보통    1
채만식  긴     1
현진건  보통    1
     짧음    1
dtype: int64

(김유정, 보통), 보통 글자수의 작품을 2편, 짧은 글자수의 작품을 1편 출품한 작가로, 비교적 단편을 많이 썼다.

In [18]:
full = pd.merge(works2, authors, on='작가', how='left')
print(full)
full.shape

     작가         작품      연도    글자수  분량    생년    몰년
0   김유정         봄봄  1935.0  12500  보통  1908  1937
1   김유정        동백꽃  1936.0   9800  짧음  1908  1937
2   김유정        만무방  1934.0  13600  보통  1908  1937
3   현진건    운수 좋은 날  1924.0  11200  보통  1900  1943
4   현진건  B사감과 러브레터  1925.0   7400  짧음  1900  1943
5    이상         날개  1936.0  18300   긴  1910  1937
6    이상         권태  1937.0  14100  보통  1910  1937
7   나도향    벙어리 삼룡이  1925.0  16800   긴  1902  1926
8   나도향       물레방아  1925.0  14500  보통  1902  1926
9   채만식   레디메이드 인생  1934.0  22000   긴  1902  1950
10  이효석   메밀꽃 필 무렵  1936.0  11800  보통  1907  1942

(11, 7)

In [19]:
works

     작가         작품      연도    글자수
0   김유정         봄봄  1935.0  12500
1   김유정        동백꽃  1936.0   9800
2   김유정        만무방  1934.0  13600
3   현진건    운수 좋은 날  1924.0  11200
4   현진건  B사감과 러브레터  1925.0   7400
5    이상         날개  1936.0  18300
6    이상         권태  1937.0  14100
7   나도향    벙어리 삼룡이  1925.0  16800
8   나도향       물레방아  1925.0  14500
9   채만식   레디메이드 인생  1934.0  22000
10  이효석   메밀꽃 필 무렵     NaN  11800

In [20]:
authors

    작가    생년    몰년
0  김유정  1908  1937
1  현진건  1900  1943
2   이상  1910  1937
3  나도향  1902  1926
4  채만식  1902  1950
5  이효석  1907  1942
6  염상섭  1897  1963

Q4 (a) 확인질문
포함되지 않는다. how 인자의 의미는 어느 표를 기준으로 살리는지이기 때문에 right 표(authors)에만 있고 left 표(works)에는 없는, 즉 'left 기준 없는 짝'은 말없이 사라진다.

In [21]:
full['집필 당시 나이'] = full['연도'] - full['생년']

full[['작가', '작품', '연도', '생년','집필 당시 나이']]

     작가         작품      연도    생년  집필 당시 나이
0   김유정         봄봄  1935.0  1908      27.0
1   김유정        동백꽃  1936.0  1908      28.0
2   김유정        만무방  1934.0  1908      26.0
3   현진건    운수 좋은 날  1924.0  1900      24.0
4   현진건  B사감과 러브레터  1925.0  1900      25.0
5    이상         날개  1936.0  1910      26.0
6    이상         권태  1937.0  1910      27.0
7   나도향    벙어리 삼룡이  1925.0  1902      23.0
8   나도향       물레방아  1925.0  1902      23.0
9   채만식   레디메이드 인생  1934.0  1902      32.0
10  이효석   메밀꽃 필 무렵  1936.0  1907      29.0

In [49]:
import pandas as pd

grouped = full.groupby('작가')['집필 당시 나이'].mean()
#작가별 집필 평균 나이를 구하여, 오름차순으로 정렬해 출력

grouped.sort_values()

작가
나도향    23.0
현진건    24.5
이상     26.5
김유정    27.0
이효석    29.0
채만식    32.0
Name: 집필 당시 나이, dtype: float64

In [50]:
full.groupby('작가')['집필 당시 나이'].mean().sort_values()

작가
나도향    23.0
현진건    24.5
이상     26.5
김유정    27.0
이효석    29.0
채만식    32.0
Name: 집필 당시 나이, dtype: float64

해석
나도향, 평균 23살. 채만식.